export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          className="relative h-screen w-screen bg-cover bg-center bg-no-repeat"
          style={{
            backgroundImage: 'url("/bg-2.png")',
          }}
        >
          {/* Blackish overlay */}
          <div className="absolute inset-0 bg-black bg-opacity-75"></div>

          {/* Content */}
          <div className="relative z-10 h-screen flex items-center justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
